`ifndef ELEMENT_MULTIPLICATION_DEFINE_STATE
`define ELEMENT_MULTIPLICATION_DEFINE_STATE


typedef enum logic[2:0] {
	S_IDLE,
	S_DATA_WAIT_0,
	S_FPMULT_0,
	S_FPMULT_1,
	S_FPMULT_2
} ElemMult_State_t;


`endif